### ISSUE TITLE
Spreadsheet link

### ISSUE THREAD

**Issue by alexprp** [gsehrlich/choreme#1]
On my android device, the hyperlink automatically generated by groupme upon posting the bot's reply includes the ".)" at the end, forcing me to either copy-paste or go to the address bar and delete those two characters to access the spreadsheet. 

I understand that this is not the case with all devices, but still suggest adding a space before the period so that we can just click. 

However, now that I'm here, I'm realizing that this public repository contains hardcoded links to our spreadsheet, and possibly other things? Would it be better to either obfuscate the link, or to move it within the GroupMe group and have the bot just point to the sidebar? As it stands, anyone can find this repo and then have access to names and activity information for our residents.

**Comment by gsehrlich** [comment]
Replaced the ".)" with ". )" (a while ago).

Also, I just got around to pushing privacy-related changes to this remote. Private info is now fetched from a separate subdirectory that is .gitignored.

**Comment by gsehrlich** [comment]
Replaced the ".)" with ". )" (a while ago).

Also, I just got around to pushing privacy-related changes to this remote. Private info is now fetched from a separate subdirectory that is .gitignored.
